### ISSUE TITLE
Add METIS Partitioning

### ISSUE THREAD

**Issue by ardasener** [sparcityeu/sparsebase#162]
The implementation should contain a wrapper class `MetisPartition` which exposes the METIS api to the user in a more SparseBase-like way. Since this is the first partitioning to be added, a `PartitionPreprocessType` should also be established.

**Comment by Atahanak** [comment]
We also need a partitioning base too.

**Comment by ardasener** [comment]
Both good ideas. I will close this issue now as the relevant PR merged. I will open two separate issues based on your suggestions.
