### ISSUE TITLE
Create a class registration file

### ISSUE THREAD

**Issue by ardasener** [sparcityeu/sparsebase#220]
Currently, our instantiation generation script has the class templates hard-coded into it. Similarly the available page in our docs has the classes hard-coded in. We could simplify this whole system by making them read from a common JSON file. The file would essentially be an array of objects where each object describes a class. Then the docs page and instantiation can be generated using this common file. 

An alternative to this would be to obtain this information by parsing the source code. However, handling `#ifdef` directives could make this quite complex.

**Comment by AmroAlJundi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a class registration file](https://trello.com/c/cVszFACX/2-create-a-class-registration-file)

**Comment by AmroAlJundi** [comment]
The next step is to somehow generate the documentation file listing all the classes of the library automatically.
